# Generated by Django 5.2.8 on 2026-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_history_likes_alter_favorite_id_alter_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
